tup=tuple(map(int,input("Enter tuple elements: ").split()))
print("Tuple elements are: ",tup)
print("Tuple length is: ",len(tup))
print("Tuple sum is: ",sum(tup))
print("Tuple max element is: ",max(tup))
print("Tuple min element is: ",min(tup))
print("Tuple average is: ",sum(tup)/len(tup))
print("Tuple sorted in ascending order is: ",sorted(tup))
print("Tuple sorted in descending order is: ",sorted(tup,reverse=True))
print("Tuple reversed is: ",tup[::-1])
